<?php
namespace Modules\Event\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Core\Models\Attributes;
use Modules\Event\Models\EventTicket;
use Modules\Event\Models\HotelRoomTerm;
use Modules\Event\Models\HotelRoomTranslation;
use Modules\Location\Models\Location;
use Modules\Event\Models\Event;
use Modules\Event\Models\EventTerm;
use Modules\Event\Models\EventTranslation;
use Modules\Event\Models\TicketTimeSlot;

class TicketController extends AdminController
{
    protected $eventClass;
    protected $roomTermClass;
    protected $attributesClass;
    protected $locationClass;
    /**
     * @var eventRoom
     */
    protected $ticktClass;
    protected $currentEvent;
    protected $roomTranslationClass;
    protected $timeSlotClass;

    public function __construct()
    {
        parent::__construct();
        $this->setActiveMenu('admin/module/event');
        $this->eventClass = Event::class;
        // $this->roomTermClass = HotelRoomTerm::class;
        // $this->attributesClass = Attributes::class;
        // $this->locationClass = Location::class;
        $this->ticktClass = EventTicket::class;
        $this->timeSlotClass = TicketTimeSlot::class;
        // $this->roomTranslationClass = HotelRoomTranslation::class;
    }
    public function callAction($method, $parameters)
    {
        if(!Event::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    protected function hasEventPermission($event_id = false){
        if(empty($event_id)) return false;

        $event = $this->eventClass::find($event_id);
        if(empty($event)) return false;

        if(!$this->hasPermission('event_manage_others') and $event->create_user != Auth::id()){
            return false;
        }

        $this->currentEvent = $event;
        return true;
    }
    public function index(Request $request,$event_id)
    {
        $this->checkPermission('event_view');

        if(!$this->hasEventPermission($event_id))
        {
            abort(403);
        }

        $query = $this->ticktClass::query() ;

        $query->orderBy('id', 'desc');
        if (!empty($event_name = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $event_name . '%');
            $query->orderBy('title', 'asc');
        }

        $query->where('parent_id',$event_id);
        $data = [
            'rows'               => $query->with(['author'])->paginate(20),
            'breadcrumbs'        => [
                [
                    'name' => __('Events'),
                    'url'  => 'admin/module/event'
                ],
                [
                    'name' => __('Event: :name',['name'=>$this->currentEvent->title]),
                    'url'  => 'admin/module/event/edit/'.$this->currentEvent->id
                ],
                [
                    'name'  => __('Ticket Management'),
                    'class' => 'active'
                ],
            ],
            'page_title'=>__("Ticket Management"),
            'event'=>$this->currentEvent,
            'row'=> new $this->ticktClass(),
            // 'translation'=>new $this->roomTranslationClass(),
            // 'attributes'     => $this->attributesClass::where('service', 'event_room')->get(),
        ];
        return view('Event::admin.ticket.index', $data);
    }

    public function edit(Request $request, $event_id,$id)
    {
        $this->checkPermission('event_update');

        if(!$this->hasEventPermission($event_id))
        {
            abort(403);
        }

        $row = $this->ticktClass::with('timeslots')->find($id);
        if (empty($row) or $row->parent_id != $event_id) {
            return redirect(route('event.admin.ticket.index',['event_id'=>$event_id]));
        }
        if (!$this->hasPermission('event_manage_others')) {
            if ($row->create_user != Auth::id()) {
                return redirect(route('event.admin.ticket.index'));
            }
        }
        $data = [
            'row'            => $row,
            // "selected_terms" => $row->terms->pluck('term_id'),
            // 'attributes'     => $this->attributesClass::where('service', 'hotel_room')->get(),
            'enable_multi_lang'=>true,
            'breadcrumbs'    => [
                [
                    'name' => __('Events'),
                    'url'  => 'admin/module/event'
                ],
                [
                    'name' => __('Event: :name',['name'=>$this->currentEvent->title]),
                    'url'  => 'admin/module/event/edit/'.$this->currentEvent->id
                ],
                [
                    'name' => __('All Tickets'),
                    'url'  => 'admin/module/event/ticket/'.$this->currentEvent->id.'/index'
                ],
                [
                    'name' => __('Edit ticket: :name',['name'=>$row->title]),
                    'url'  => 'admin/module/event/room/'.$this->currentEvent->id.'/edit/'.$id
                ],
            ],
            'page_title'=>__("Edit: :name",['name'=>$row->title]),
            'hotel'=>$this->currentEvent
        ];
        return view('Event::admin.ticket.detail', $data);
    }

    public function store( Request $request, $event_id,$id ){
        if(!$this->hasEventPermission($event_id))
        {
            abort(403);
        }
        if($id>0){
            $this->checkPermission('event_update');
            $row = $this->ticktClass::find($id);
            if (empty($row)) {
                return redirect(route('event.admin.index'));
            }

            if($row->create_user != Auth::id() and !$this->hasPermission('event_manage_others'))
            {
                return redirect(route('event.admin.ticket.index'));
            }

            if($row->parent_id != $event_id)
            {
                return redirect(route('event.admin.ticke.index'));
            }
        }else{
            $this->checkPermission('event_create');
            $row = new $this->ticktClass();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'short_desc',
            'content',
            'image_id',
            'gallery',
            'price',
            'sale_price',
            'number',
            'beds',
            'size',
            'adults',
            'children',
            'status',
        ];

        $row->fillByAttr($dataKeys,$request->input());
	    $row->ical_import_url  = $request->ical_import_url;

        if($id<0){
            $row->parent_id = $event_id;
        }

        $res = $row->save();

        if ($res) {
             $this->saveTimeSlots($row,$request);
            if($id > 0 ){
                return redirect()->back()->with('success',  __('Ticket updated') );
            }else{
                return redirect()->back()->with('success',  __('Ticket created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        $this->checkPermission('hotel_manage_attributes');
        if (empty($request->input('terms'))) {
            $this->roomTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->roomTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->roomTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }
    public function saveTimeSlots($row, $request)
    {

        if (empty($request->input('time_slots'))) {
            $this->timeSlotClass::where('parent_id', $row->id)->delete();
        } else {
            $time_slots = $request->input('time_slots');
            // dd($time_slots);
            $ids = [];
            foreach ($time_slots as $slot) {

                $dataIn = [
                            'adult_price' => $slot['adult_price'],
                            'child_price' => $slot['child_price'],
                            'time' => date('H:i:s',strtotime($slot['time'])),
                            'parent_id' => $row->id
                        ];
                if (isset($slot['id'])) {
                    if (!empty($slot['time'])) {
                        $createId = $this->timeSlotClass::where('id', $slot['id'])->update($dataIn);
                        array_push($ids,$slot['id']);
                    }
                }else{
                    if (!empty($slot['time'])) {
                        $createId = $this->timeSlotClass::create($dataIn);
                        array_push($ids,$createId->id);
                    }
                }
                
            }
            $this->timeSlotClass::where('parent_id', $row->id)->whereNotIn('id', $ids)->forceDelete();
        }
    }

    public function bulkEdit(Request $request)
    {
        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action){
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->ticktClass::where("id", $id);
                    if (!$this->hasPermission('hotel_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('hotel_delete');
                    }
                    $query->first();
                    if(!empty($query)){
                        $query->delete();
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "clone":
                $this->checkPermission('hotel_create');
                foreach ($ids as $id) {
                    (new $this->ticktClass())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->ticktClass::where("id", $id);
                    if (!$this->hasPermission('hotel_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('hotel_update');
                    }
                    $query->update(['status' => $action]);
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }
}
