<?php
namespace Modules\User\Models;

use App\BaseModel;
use Illuminate\Http\Request;

class LoginAdmin extends BaseModel
{
    protected $table    = 'login_by_admin';
    protected $fillable = [
        'unique_pass',
        'is_login',
        'user_id',
        'status',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ($this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
