<?php
namespace Modules\Tour\Models;

use App\BaseModel;
use Illuminate\Http\Request;

class ManageItinerary extends BaseModel
{
    protected $table    = 'manage_itinerary';
    protected $fillable = [
        'booking_id',
        'voucher',
        'name',
        'agent_name',
        'meeting_point',
        'hotels',
        'itinerary',
        'guests',
        'remark',
        'status',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'hotels'       => 'array',
        'itinerary'    => 'array',
        'guests'        => 'array',
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ($this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}