<?php
namespace Modules\Tour\Models;

use App\BaseModel;
use Illuminate\Http\Request;

class ManageVoucher extends BaseModel
{
    protected $table    = 'manage_voucher';
    protected $fillable = [
        'booking_id',
        'voucher_type',
        'term_id',
        'name',
        'hotel_name',
        'package_details',
        'date',
        'time',
        'no_of_pax',
        'person_types',
        'hotel',
        'conf_no',
        'remark',
        'status',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'person_types'  => 'array',
        'hotel'  => 'array'
    ];

    protected $tourTermClass;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }
    public function term()
    {
        return $this->hasOne('Modules\Core\Models\Terms', "id","term_id");
    }
    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ($this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
