<?php
namespace Modules\Lead\Models;

use App\BaseModel;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class LeadEmail extends BaseModel
{
    use SoftDeletes;
    protected $table    = 'emails';
    protected $fillable = [
        'enquiry_id',
        'phone',
        'emails',
        'subject',
        'content',
        'status',
        'attachment',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'emails' => 'array'
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ($this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
