<?php
namespace Modules\Lead\Models;

use App\BaseModel;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class LeadReminder extends BaseModel
{
    // use SoftDeletes;
    protected $table    = 'reminders';
    protected $fillable = [
        'enquiry_id',
        'phone',
        'date',
        'content',
        'status',
        'read_status',
        'type',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ($this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
    public function enquiry()
    {
        return $this->hasOne("Modules\Booking\Models\Enquiry", "id", 'enquiry_id');
    }

    public function CreateUser()
    {
        return $this->hasOne("App\User", "id", 'create_user');
    }
    public function UpdateUser()
    {
        return $this->hasOne("App\User", "id", 'update_user');
    }
}
