<?php
namespace Modules\Lead\Models;

use App\BaseModel;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class LeadHistory extends BaseModel
{
    // use SoftDeletes;
    protected $table    = 'lead_history';
    protected $fillable = [
        'enquiry_id',
        'phone',
        'type',
        'content',
        'status'
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ($this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
