<?php
namespace Modules\Booking\Models;

use App\BaseModel;
use Illuminate\Http\Request;

class BookingProposal extends BaseModel
{
    protected $table    = 'booking_proposal';
    protected $fillable = [
        'enquiry_id',
        'tour_id',
        'tour_details',
        'destination',
        'name',
        'duration',
        'start_date',
        'end_date',
        'default_hotels',
        'itinerary',
        'extra_price',
        'discount_by_people',
        'person_types',
        'welcome_note',
        'term_condations',
        'cancellation_note',
        'tips',
        'other_note',
        'thankyou_note',
        'total_price',
        'discount',
        'total_tour_price',
        'remark',
        'booking_status',
        'status',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'default_hotels'       => 'array',
        'itinerary'    => 'array',
        'extra_price'        => 'array',
        'discount_by_people'        => 'array',
        'tour_details'        => 'array',
        'person_types'        => 'array'
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ($this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
