<?php
namespace Modules\Contact\Models;

use App\BaseModel;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
class ForexOrderItems extends BaseModel
{
    use SoftDeletes;
    protected $table = 'forex_ordered_item';

    protected $fillable = [
        'order_id',
        'type',
        'country_id',
        'pay_type',
        'forex_amount',
        'inr_amount',
        'forex_rate',
        'status',
        'vendor_id',
    ];
    protected $casts = [
        'meta_data' => 'array'
    ];

    public static $enquiryStatus = [
        'pending',
        'completed',
        'cancel',
    ];

 public function ForexCountry()
    {
        return $this->belongsTo('Modules\Forex\Models\ForexCountry', 'country_id');
    }
    public function fill(array $attributes)
    {
        if (!empty($attributes)) {
            foreach ($this->fillable as $item) {
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }

    public function getStatusNameAttribute()
    {
        return booking_status_to_text($this->status);
    }
    public function CreateUser()
    {
        return $this->hasOne("App\User", "id", 'create_user');
    }
    public function UpdateUser()
    {
        return $this->hasOne("App\User", "id", 'update_user');
    }
}
