<?php
namespace Modules\Contact\Models;

use App\BaseModel;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
class ForexOrders extends BaseModel
{
    use SoftDeletes;
    protected $table = 'forex_order';

    protected $fillable = [
        'name',
        'email',
        'phone',
        'city',
        'date',
        'note',
        'status',
    ];
    protected $casts = [
    ];

    public static $enquiryStatus = [
        'pending',
        'completed',
        'cancel',
    ];

    public function fill(array $attributes)
    {
        if (!empty($attributes)) {
            foreach ($this->fillable as $item) {
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }

    public function getStatusNameAttribute()
    {
        return booking_status_to_text($this->status);
    }
    public function CreateUser()
    {
        return $this->hasOne("App\User", "id", 'create_user');
    }
    public function UpdateUser()
    {
        return $this->hasOne("App\User", "id", 'update_user');
    }
}
